### ISSUE TITLE
Unable to install on Lubuntu 16.04

### ISSUE THREAD

**Issue by bparticle** [ayyi/samplecat#23]
Hi, I am very motivated to get this piece of software working on my machine but I can't seem to install it from source on Lubuntu 16.04. I have limited experience with the process and I assume that is the only problem. I have tried three sources: the official stable one, the latest snapshot and the Git repository. They give me different results but none of them work. The repository does install the software, but with many warnings.

After fixing a lot of dependencies, configure seems to be working fine, although it says Jack and MySQL is not available. They are both installed and working, however. This is the configure end message:

> Libwaveform:
> Building opengl:          yes
> Building sdl:             no
> Building libass:          yes
> Building ffmpeg:          no
> Building tests:           no
> Building lv2:             no (TODO)
> 
> Database backend:
>   mysql support:              no
>   sqlite support:             no
> Audio decoders:
>   libsndfile:                 yes
>   ffmpeg decoder:             no
> Audio players:
>   built-in JACK:              no
>   AYYI/Dbus:                  no
>   CLI: gst,afplay,totem:      yes
> Building zlib:                yes
> Building dnotify support:     yes
> Building inotify support:     yes
> Building opengl support:      yes
> Building libass support:      yes
> Building ayyi support:        no
> Building dock support:        yes

**Make** fails with the following message:

> sample.c:18:24: fatal error: decoder/ad.h: No such file or directory
> compilation terminated.
> Makefile:492: recipe for target 'sample.o' failed
> make[4]: **\* [sample.o] Error 1
> make[4]: Leaving directory '/opt/samplecat/lib/samplecat'
> Makefile:525: recipe for target 'all-recursive' failed
> make[3]: **\* [all-recursive] Error 1
> make[3]: Leaving directory '/opt/samplecat/lib/samplecat'
> Makefile:415: recipe for target 'all-recursive' failed
> make[2]: **\* [all-recursive] Error 1
> make[2]: Leaving directory '/opt/samplecat/lib'
> Makefile:541: recipe for target 'all-recursive' failed
> make[1]: **\* [all-recursive] Error 1
> make[1]: Leaving directory '/opt/samplecat'
> Makefile:430: recipe for target 'all' failed
> make: **\* [all] Error 2

Is there any more information I can give, or commands I can run as to pinpoint the problem here?
Many thanks in advance!

Bruno

**Comment by ayyi** [comment]
Hi, sorry for the delay in replying.

Do you have the devel packages installed? For example for sqllite you will need the sqllite-devel package (or whatever it is called on your distro)

Regarding the missing decoder/ad.h file, it is likely that this can be fixed by running the command
``
git submodule foreach git pull origin master
``

Hope that helps

**Comment by bparticle** [comment]
No probs, thanks for helping! I have now directly worked with the repository and followed your suggestions, but get stuck on "libwaveform submodule missing". I have installed libwaveform without errors prior to my attempting to install samplecat, however. Before, the submodule was automatically pulled in. 
The command `git submodule foreach git pull origin master` does not give me any helpful output and doesn't seem to do anything.

**Comment by bparticle** [comment]
The program seems to install without errors (I do get warnings about a certain subdirectory option).
When I try to launch it, however, it gives me the following error.
```
Samplecat. Version 0.2.5
database is sqlite.
warning: default icon theme appears not to contain audio mime-type icons
Illegal instruction (core dumped)
```

**Comment by bengan** [comment]
I get the same error as @bparticle 

sample.c:18:24: fatal error: decoder/ad.h: No such file or directory
compilation terminated.
make[4]: *** [Makefile:491: sample.o] Error 1
make[4]: Leaving directory '/home/bengan/src/samplecat/lib/samplecat'
make[3]: *** [Makefile:524: all-recursive] Error 1
make[3]: Leaving directory '/home/bengan/src/samplecat/lib/samplecat'
make[2]: *** [Makefile:414: all-recursive] Error 1
make[2]: Leaving directory '/home/bengan/src/samplecat/lib'
make[1]: *** [Makefile:540: all-recursive] Error 1
make[1]: Leaving directory '/home/bengan/src/samplecat'
make: *** [Makefile:429: all] Error 2

I've got ad.h
$ find . -name ad.h
./lib/waveform/decoder/ad.h

I followed the README file with all submodules.
        git submodule init
        git submodule update
        git submodule foreach git pull origin master

and then
./autogen.sh && ./configure && make

I'm on opensuse tumbleweed.

**Comment by bengan** [comment]
I'm guessing something went wrong here
git show e1bd084dfa12c7b9a835b6c263b4783d24dc0dcd

**Comment by MaxWorgan** [comment]
I'm got the same issue:

sample.c:18:24: fatal error: decoder/ad.h: No such file or directory
compilation terminated.

**Comment by MaxWorgan** [comment]
It takes a very small edit to make it find the waveform libs:
https://github.com/MaxWorgan/samplecat/commit/228a526b3949922e28e54a936ae5490bc169aed8 
and it now builds.

However, on starting the application, it segfaults < 1 second after the gui is displayed.
I'll look into it further when I've got some free time.

**Comment by MaxWorgan** [comment]
The crash occurs inside the gtk_main loop

Here is a stack trace: http://pastebin.com/YynH84Xz

I have gtk2 2.24.31 installed

I hope this might help - I have very little experience with C and/or gtk

**Comment by nodiscc** [comment]
@ayyi can you apply the patch recommended by @MaxWorgan in https://github.com/MaxWorgan/samplecat/commit/228a526b3949922e28e54a936ae5490bc169aed8 ? It fixes the build error `sample.c:18:24: fatal error: decoder/ad.h: No such file or directory` for me.

**Comment by ayyi** [comment]
Apologies for the delay. Compilation should be fixed now. Thanks, everyone for your comments.

**Comment by ayyi** [comment]
@MaxWorgan Thanks for the backtrace. It appears to be crashing while trying to create one of the gtk widgets. I will create a new issue for this.

**Comment by naught101** [comment]
@ayyi I'm still seeing that `decoder/ad.h` error mentioned above. The fix in nodiscc's comment doesn't seem to be implemented, but also doesn't seems to fix it. Any other ideas for how to get it working? I'm running kubuntu 17.10.

**Comment by ayyi** [comment]
@naught101 Please check you don't have an old 'waveform' directory in /usr/local/include or similar. However you will have to bear with me as Samplecat does not run when compiled with the default compiler on kubuntu-17. I will commit a fix for this in a few days time. Thanks for your patience.

**Comment by naught101** [comment]
I don't have anything in `/usr/local/include/`. Keen to check out the new version.
